"""
Generate the app's and the site's colour tokens from design/tokens.json.

    python tools/build_tokens.py          # rewrite the generated files
    python tools/build_tokens.py --check  # exit 1 if any generated file is stale

Writes:
  DesktopApp/Styles/Tokens.xaml         dark theme (the app's current theme)
  DesktopApp/Styles/Tokens.Light.xaml   light theme (not loaded until the app gains one)
  Website/styles.css                    only the text between the tokens:light and
                                        tokens:dark markers; the rest is hand-written

Colours used to be typed twice, once in Theme.xaml and once in styles.css, and
the two drifted. This makes the JSON the only place a colour is defined.
See DESIGN_SYSTEM.md, section 14.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
XAML_OUT = {
    "dark": ROOT / "DesktopApp" / "Styles" / "Tokens.xaml",
    "light": ROOT / "DesktopApp" / "Styles" / "Tokens.Light.xaml",
}
CSS = ROOT / "Website" / "styles.css"

HEADER = "Generated by tools/build_tokens.py from design/tokens.json. Do not edit by hand."


def _hex(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    if not re.fullmatch(r"[0-9A-Fa-f]{6}", value):
        raise ValueError(f"not a #RRGGBB colour: #{value}")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def resolve(theme: dict, name: str, seen: tuple[str, ...] = ()) -> tuple[int, int, int, float]:
    """A token as (r, g, b, alpha), following {"ref", "alpha"} references."""
    if name in seen:
        raise ValueError(f"circular token reference: {' -> '.join(seen + (name,))}")
    value = theme[name]
    if isinstance(value, str):
        return (*_hex(value), 1.0)
    r, g, b, _ = resolve(theme, value["ref"], seen + (name,))
    return r, g, b, float(value["alpha"])


def _alpha_byte(alpha: float) -> int:
    return max(0, min(255, round(alpha * 255)))


def _fmt_alpha(alpha: float) -> str:
    return f"{alpha:.2f}".rstrip("0").rstrip(".") if alpha not in (0, 1) else str(int(alpha))


def xaml(data: dict, theme_name: str) -> str:
    theme = data["themes"][theme_name]
    lines = [
        '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
        f"    <!-- {HEADER} Theme: {theme_name}. -->",
        "",
    ]
    for token, key in data["app_names"].items():
        r, g, b, a = resolve(theme, token)
        argb = f"#{_alpha_byte(a):02X}{r:02X}{g:02X}{b:02X}"
        lines.append(f'    <Color x:Key="{key}Color">{argb}</Color>')
    lines.append("")
    for token, key in data["app_names"].items():
        lines.append(f'    <SolidColorBrush x:Key="{key}" Color="{{StaticResource {key}Color}}"/>')
    lines += ["</ResourceDictionary>", ""]
    return "\n".join(lines)


def css_block(data: dict, theme_name: str, indent: str = "  ") -> str:
    theme = data["themes"][theme_name]
    skip = set(data.get("css_skip", []))
    out = [f"{indent}/* {HEADER} */"]
    for token in theme:
        if token in skip:
            continue
        r, g, b, a = resolve(theme, token)
        value = f"#{r:02x}{g:02x}{b:02x}" if a == 1.0 else f"rgba({r}, {g}, {b}, {_fmt_alpha(a)})"
        out.append(f"{indent}--color-{token}: {value};")
    out.append("")
    for name, value in data["css_only"][theme_name].items():
        out.append(f"{indent}--{name}: {value};")
    return "\n".join(out)


def css(data: dict, current: str) -> str:
    """Replace each marked block in styles.css, leaving everything else untouched."""
    updated = current
    for theme_name in ("light", "dark"):
        pattern = re.compile(
            rf"(/\* tokens:{theme_name}:start \*/\r?\n)(.*?)(\r?\n[ \t]*/\* tokens:{theme_name}:end \*/)",
            re.S,
        )
        if not pattern.search(updated):
            raise ValueError(f"styles.css is missing the tokens:{theme_name} markers")
        block = css_block(data, theme_name)
        updated = pattern.sub(lambda m: m.group(1) + block + m.group(3), updated, count=1)
    return updated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--check", action="store_true",
                        help="report stale generated files instead of writing them")
    args = parser.parse_args()

    data = json.loads(TOKENS.read_text(encoding="utf-8"))

    wanted: dict[Path, str] = {path: xaml(data, theme) for theme, path in XAML_OUT.items()}
    wanted[CSS] = css(data, CSS.read_bytes().decode("utf-8").replace("\r\n", "\n"))

    stale = []
    for path, content in wanted.items():
        # Compare ignoring line endings: git checks files out with CRLF on
        # Windows and LF elsewhere (.gitattributes text=auto).
        existing = path.read_bytes().decode("utf-8").replace("\r\n", "\n") if path.exists() else None
        if existing != content.replace("\r\n", "\n"):
            stale.append(path)
            if not args.check:
                path.write_bytes(content.encode("utf-8"))

    rel = [str(p.relative_to(ROOT)) for p in stale]
    if args.check:
        if stale:
            print("stale generated token files (run python tools/build_tokens.py): " + ", ".join(rel))
            return 1
        print("token files are up to date")
        return 0
    print("wrote: " + (", ".join(rel) if rel else "nothing (already up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
