/*
 * FlowShield site configuration.
 *
 * Only PUBLIC values belong in this file — it is committed and served to every
 * visitor. A Stripe Payment Link URL is public by design; secret keys never
 * appear here and live only in .stripe_keys.json, which is git-ignored.
 *
 * Generated by `node tools/setup_stripe_store.js` on 2026-09-11T12:25:35.637Z.
 */
window.FLOWSHIELD_CONFIG = {
  /*
   * Stripe Payment Link — a Stripe-hosted checkout page that needs no backend.
   * This is what the published, static site uses: GitHub Pages cannot run the
   * license server, and a visitor's browser obviously cannot reach ours.
   */
  paymentLink: "https://buy.stripe.com/test_aFaeVcgRp74752td0fcZa01",

  /*
   * License server base URL. Empty on the public build.
   *
   * When set, the site prefers it over the Payment Link because that flow also
   * reserves a license key up front and can hand it straight back on the
   * success page. Override per-visit with ?server=http://host:port.
   */
  licenseServerUrl: "https://flowshield-license-server.onrender.com",

  /* Shown on the success page so buyers know where their key comes from. */
  supportEmail: "",
};
