using System.Text.RegularExpressions;
using Microsoft.Win32;

namespace FlowShield.Services;

/// <summary>
/// flowshield:// links (roadmap 1.4).
///
/// The success page's "Activate in FlowShield" button opens
/// flowshield://activate?key=FS-…. The only thing a link can do is put a
/// well-formed key in front of the user for one confirming click: a web page
/// must never be able to activate, change a setting or start anything by itself.
/// </summary>
public static partial class DeepLink
{
    public const string Scheme = "flowshield";
    public const string ClassesKey = @"Software\Classes\" + Scheme;

    // Crockford base32, as generated by Server/licensekey.js. The server checks
    // the checksum; this only stops anything that isn't shaped like a key.
    [GeneratedRegex(@"^FS-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}$")]
    private static partial Regex KeyShape();

    /// <summary>The licence key from an activation link, or null for anything else.</summary>
    public static string? ParseActivationKey(string? link)
    {
        if (string.IsNullOrWhiteSpace(link)) return null;
        if (!Uri.TryCreate(link.Trim(), UriKind.Absolute, out var uri)) return null;
        if (!uri.Scheme.Equals(Scheme, StringComparison.OrdinalIgnoreCase)) return null;

        // flowshield://activate?… puts "activate" in the host; tolerate a trailing slash.
        var action = (uri.Host + uri.AbsolutePath).Trim('/');
        if (!action.Equals("activate", StringComparison.OrdinalIgnoreCase)) return null;

        string? key = null;
        foreach (var pair in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))
        {
            var parts = pair.Split('=', 2);
            if (parts.Length == 2 && parts[0].Equals("key", StringComparison.OrdinalIgnoreCase))
                key = Uri.UnescapeDataString(parts[1]).Trim().ToUpperInvariant();
        }
        return key is not null && KeyShape().IsMatch(key) ? key : null;
    }

    /// <summary>The first flowshield:// argument a launch was given, if any.</summary>
    public static string? FindLink(IEnumerable<string> args) =>
        args.FirstOrDefault(a => a.StartsWith(Scheme + ":", StringComparison.OrdinalIgnoreCase));

    /// <summary>Registers flowshield:// for this user. Called from Velopack's install and update hooks.</summary>
    public static void Register(string exePath)
    {
        try
        {
            using var root = Registry.CurrentUser.CreateSubKey(ClassesKey);
            root.SetValue("", "URL:FlowShield");
            root.SetValue("URL Protocol", "");
            using (var icon = root.CreateSubKey("DefaultIcon")) icon.SetValue("", $"\"{exePath}\",0");
            using var command = root.CreateSubKey(@"shell\open\command");
            command.SetValue("", $"\"{exePath}\" \"%1\"");
            Log.Info("flowshield:// registered");
        }
        catch (Exception ex)
        {
            Log.Error("could not register flowshield://", ex);
        }
    }

    /// <summary>Removes the registration. Called from Velopack's uninstall hook.</summary>
    public static void Unregister()
    {
        try
        {
            Registry.CurrentUser.DeleteSubKeyTree(ClassesKey, throwOnMissingSubKey: false);
            Log.Info("flowshield:// removed");
        }
        catch (Exception ex)
        {
            Log.Error("could not remove flowshield://", ex);
        }
    }
}
